channels:
- conda-forge
dependencies:
- python=3.10.10
- pip<=22.3.1
- pip:
  - mlflow==2.9.2
  - numpy==1.26.2
  - pandas==2.1.4
  - psutil==5.9.7
  - scikit-learn==1.3.2
  - scipy==1.11.4
  - xgboost==2.0.3
name: mlflow-env
